name: calsnap
description: AI Calorie Counter with Camera Scan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_generative_ai: ^0.4.3
  image_picker: ^1.1.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  gap: ^3.0.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.69.0
  confetti: ^0.7.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  intl: ^0.19.0
  google_mobile_ads: ^5.1.0
  purchases_flutter: ^8.0.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
